const studentInfo = {
  uz: {
    talaba: {
      b1: "Goipova Shaxnoza Saidazim qizi",
      p1: "Tayanch doktorantlar (PhD) uchun Oʻzbekiston Respublikasi Prezidenti stipendiyasi sohibi",
      b2: "Erkinov Farrux Botir o‘g‘li",
      p2: "Tayanch doktorantlar (PhD) uchun Oʻzbekiston Respublikasi Prezidenti stipendiyasi sohibi",
      b3: "Tirkasheva Xurshida Otabek qizi",
      p3: "2021/2022 o’quv yilida Oʻzbekiston Respublikasi Prezidenti stipendiyasi sohibi",
      b4: "Mirraxmadov Jaxongir Alisher o‘g‘li",
      p4: "2022/2023 o’quv yilida Oʻzbekiston Respublikasi Prezidenti stipendiyasi sohibi",
      b5: "Tursunova Dilnoza Isroiljon qizi",
      p5: "2021/2022 o’quv yilida magistrlar uchun Oʻzbekiston Respublikasi Prezidenti stipendiyasi sohibi 2021-yil “Zulfiya” mukofoti sovrindori",
      b6: "Nabiyeva Nilufar Baxtiyor qizi",
      p6: "2021/2022o’quv yilida Beruniy nomidagi stipendiyasi sohibasi",
      b7: "Kozimjonova Arofat Ilxomjon qizi",
      p7: "2021/2022o’quv yilida Beruniy nomidagi stipendiyasi sohibasi Bir nechta xalqaro seminarlarda koordinator",
      b8: "Bekmuradova Sabina Qutlug’ qizi",
      p8: "2022/2023 o’quv yilida Beruniy nomidagi davlat stipendiyasi sohibasi. Institut Start-up loyixalar tanlovi g’olibi. Yoshlar akademiyasi a’zosi",
      b9:"Jo’raqulova Zulayxo Ixtiyor qizi",
      p9:"2022/2023 o’quv yilida Beruniy nomidagi davlat stipendiyasi sohibasi, Institutda ta’sis etilgan Akademik Xusniddin Rustamov stipendiyasisohibi",
      b10:"Akromova Malika Davronovna",
      p10:"2022/2023 o’quv yilida Beruniy nomidagi davlat stipendiyasi sohibasi, Institut Start-up loyixalar tanlovi g’olibi, Yoshlar akademiyasi a’zosi",
      b11:"Muxammadiyev Nodir Ikromjon o’g’li",
      p11:"2022/2023 o’quv yilida Islom Karimov nomidagi davlat stipendiyasi sohibasi",
      b12:"To‘xtamurodova Farzona",
      p12:"2022/2023o’quv yilida Akademik Anna Glushenkova stipendiyasi sohibi",
      b13:"Ruzmetova Sabinabonu Baxrom qizi",
      p13:"2022/2023o’quv yilida Akademik Anna Glushenkova stipendiyasi sohibi",
      b14:"Pardayev Asadbek",
      p14:"2022/2023 o’quv yilidaAkademik Karim Ahmedov stipendiyasi  sohibi, 1. O'zbekiston GTL stipendiya dasturi  g\'olibi, 3.Student fest 2022-tanlovida Kimyo fanida 3-o'rin sohibi",
      b15:"Maxmudova Mashxura Komil qizi",
      p15:"2021/2022 o’quv yilida Akademik Anna Glushenkova stipendiyasi sohibi",
      b16:"Sersenbayeva Aliya Shuxrat qizi",
      p16:"2021/2022o’quv yilida Akademik Zokirjon Salimov stipendiyasi sohibi",
      b17:"Balzakova Balnurа",
      p17:"Institutda o’tkazilgan Start-Up loyihalar tanlovi g’olibi",
      b18:"Usmonaliyeva E'zoza",
      p18:"Institutda o’tkazilgan Start-Up loyihalar tanlovi g’olibi",
      b19:"Халилов Махмуд",
      p19:"O'zbekiston GTL stipendiya dasturi   g'olibi",
      b20:"Jumanazarov Ma’murjon",
      p20:"Yoshlar akademiyasi a’zosi, Boʻlajak olim tanlovida gʻolib boʻlganligi uchun rahbarligidagi loyihasi 600 000 000soʻm bilan moliyalashtirildi. ",
      b21:"Normurodov Olmos",
      p21:"2021/2022o’quv yilida Ibroyim Yusupov stipendiyasi sohibi",
b22:"Jaylashova Dilbar",
p22:"2021/2022o’quv yilida Ibroyim Yusupov stipendiyasi sohib",
b23:"Tolibjonov Saidazimxon Nodirjon o’g’li",
p23:"Yoshlar akademiyasi a’zosi, 2021/2022 o’quv yilida Akademik To‘lqin Mirkomilov stipendiyasi sohibi, Institutda o’tkazilgan Start-Up loyihalar tanlovi g’olibi"

    },
    graduates: {
      first:
        "Toshkent kimyo-texnologiya institutida juda ko‘plab iqtidorli yoshlar taxsil olishadi. Bu talaba-yoshlarimiz ko‘pgina yutuqlarga erishib kelishmoqda.  Biz bu talaba-yoshlarimiz bilan faxrlanamiz",
      second: "Iqtidorli talabalar",
    }
  },
  ru: {
    talaba: {
      b1: "Гаипова Шахноза Саидазим кизи",
      p1: "Обладатель стипендии Президента Республики Узбекистан для базовых докторантов (PhD).",
      b2: "Эркинов Фаррух Ботир угли",
      p2: "Обладатель стипендии Президента Республики Узбекистан для базовых докторантов (PhD).",
      b3: "Тиркашева Хуршида Отабек кизи",
      p3: "В 2021/2022 учебном году стипендиат Президента Республики Узбекистан",
      b4: "Миррахмадов Джахонгир Алишер  угли",
      p4: "В 2022/2023 учебном году стипендиат Президента Республики Узбекистан",
      b5: "Турсунова Дильноза Исроилжон кизи",
      p5: "В 2021/2022 учебном году обладатель стипендии Президента Республики Узбекистан для магистров Лауреат премии «Зульфия» 2021 года. ",
      b6: "Набиева Нилуфар Бахтияр кизи ",
      p6: "В 2021/2022 учебном году является обладательницей стипендии имени Беруни.",
      b7: "Козимжонова Арофат Илхомжон қизи",
      p7: "В 2021/2022 учебном году является обладательницей стипендии имени Беруни. Координатор нескольких международных семинаров ",
      b8: "Бекмурадова Сабина Кутлуг кизи",
      p8: "В 2021/2022 учебном году является обладательницей стипендии имени Беруни.Координатор нескольких международных семинаров",
      b9:"Джоракулова Зулайхо Ихтияр кизи",
      p9:"В 2022/2023 учебном году является обладательницей государственной стипендии имени Беруни. В институте учреждена стипендия академика ХусниддинаРустамова",
      b10:"Малика Акромова Давроновна",
      p10:"В 2022/2023 учебном году является обладательницей государственной стипендии имени Беруни. Институт – победитель конкурса Start-up проектов. Член Молодежной Академии",
      b11:"Мухаммадиев Надир Икромжон угли",
      p11:"В 2022/2023 учебном году является обладательницей государственной стипендии имени Ислама Каримова.",
      b12:"Фарзона Тохтамуродова",
      p12:"В 2022/2023 учебном году является стипендиатом академической стипендии Анны Глушенковой.",
      b13:"Рузметова Сабинабону Бахромкизи",
      p13:"В 2022/2023 учебном году является стипендиатом академической стипендии Анны Глушенковой.",
      b14:"Пардаев Асадбек",
      p14:"В 2022/2023 учебном году он является стипендиатом академика Карима Ахмедова. 2.Победитель стипендиальной программы GTL в Узбекистане. 3. Обладатель 3 места по химии на конкурсе StudentFest 2022",
      b15:"Махмудова Машхура Камиль",
      p15:"В 2021/2022 учебном году является стипендиатом академической стипендии Анны Глушенковой.",
      b16:"Серсенбаева Алия Шухрат кизи",
      p16:"В 2021/2022 учебном году является стипендиатом академической стипендии Закиржон Салимов ",
      b17:"Бальзакова Бальнура",
      p17:"Победитель конкурса Start-Up проектов, проводимого в институте",
      b18:"Усмоналиева Эзоза",
      p18:"Победитель конкурса Start-Up проектов, проводимого в институте",
      b19:"Халилов Махмуд",
      p19:"Победитель стипендиальной программы GTL в Узбекистане",
      b20:"Джуманазаров Мамуржон",
      p20:"Член Молодежной Академии. Проект под его руководством был профинансирован на 600 000 000 сомов для победы в конкурсе будущих ученых. ",
      b21:"Нормуродов Алмас",
      p21:"В 2021/2022 учебном году стипендиат Ибраима Юсупова",
      b22:"Джайлашова Дильбар",
      p22:"В 2021/2022 учебном году стипендиат Ибраима Юсупова",
      b23:"Талибжанов Сайдазимхан Нодиржан",
      p23:"Член Молодежной Академии. В 2021/2022 учебном году он является лауреатом академической стипендии Толкина Миркомилова.Победитель конкурса Start-Up проектов, проводимого в институте ",
    },
    graduates: {
      first:
        "В Ташкентском химико-технологическом институте учится много одарённые молодежи. На молодёжи добиваются многих успехов. Мы гордимся нашими молодёжими.",
      second: "одаренные студенты",
    }
  },
  en: {
    talaba: {
      b1: "Gaipova Shakhnoza Saidazim  qizi ",
      p1: "Holder of the scholarship of the President of the Republic of Uzbekistan for basic doctoral students (PhD).",
      b2: "Erkinov Farrukh Botir o‘g‘li",
      p2: "Holder of the scholarship of the President of the Republic of Uzbekistan for basic doctoral students (PhD).",
      b3: "Tirkasheva Khurshida Otabek  qizi",
      p3: "In the 2021/2022 academic year, the scholarship holder of the President of the Republic of Uzbekistan",
      b4: "Mirrahmadov Jahongir Alisher o‘g‘li",
      p4: "In the 2022/2023 academic year, the scholarship holder of the President of the Republic of Uzbekistan",
      b5: "Tursunova Dilnoza Isroiljon qizi",
      p5: "In the 2021/2022 academic year, the holder of the scholarship of the President of the Republic of Uzbekistan for masters Winner of the Zulfiya Prize 2021.",
      b6: "Nabiyeva Nilufar Bakhtiyar qizi",
      p6: "In the 2021/2022 academic year, she is the owner of the Beruni scholarship.",
      b7: "Kozimjonova Arofat Ilxomjon qizi",
      p7: "In the 2021/2022 academic year, she is the owner of the Beruni scholarship. Coordinator of severalinternational seminars",
      b8: "Bekmuradova Sabina Kutlug qizi",
      p8: "In the 2022/2023 academic year, she is the owner of the state scholarship named after Beruni. The Institute is the winner of the Start-up projects competition",
      b9:"o’raqulova Zulayxo Ixtiyor qizi",
      p9:"In the 2022/2023 academic year, she is the owner of the state scholarship named after Beruni. Academician Khusniddin Rustamov's scholarship was established at the Institute",
      b10:"Akromova Malika Davronovna",
      p10:"In the 2022/2023 academic year, she is the owner of the state scholarship named after Beruni. The Institute is the winner of the Start-up projects competition",
      b11:"Muxammadiyev Nodir Ikromjon o’g’li",
      p11:"In the 2022/2023 academic year, she is the owner of the state scholarship named after Islam Karimov.",
      b12:"To‘xtamurodova Farzona",
      p12:"In the 2022/2023 academic year, she is a scholarship holder of the Anna Glushenkova Academic Scholarship.",
      b13:"Ruzmetova Sabinabonu Baxrom qizi",
      p13:"In the 2022/2023 academic year, she is a scholarship holder of the Anna Glushenkova Academic Scholarship.",
      b14:"Pardayev Asadbek",
      p14:"In the 2022/2023 academic year, he is a scholarship holder of academician Karim Akhmedov. GTL Scholarship Program Winner in Uzbekistan 2. 3rd place winner in the nomination \"The most knowledgeable student of the year\" (according to specialty) at the institute stage of the \"Student of the Year 2022\" competition. 3. Winner of 3rd place in Chemistry at the Student Fest 2022 competition",
      b15:"Maxmudova Mashxura Komil qizi",
      p15:"In the 2021/2022 academic year, she is a scholarship holder of the Anna Glushenkova Academic Scholarship.",
      b16:"Sersenbayeva Aliya Shuxrat qizi",
      p16:"In the 2021/2022 academic year, she is a scholarship holder of the Zakirjon Salimov received a scholarship",
      b17:"Balzakova Balnurа",
      p17:"Winner of the competition Start-Up projects held at the institute",
      b18:"Usmonaliyeva E'zoza",
      p18:"Winner of the competition Start-Up projects held at the institute",
      b19:"Халилов Махмуд",
      p19:"GTL Scholarship Program Winner in Uzbekistan",
      b20:"Jumanazarov Ma’murjon",
      p20:"Member of the Youth Academy. The project under his leadership was funded by 600,000,000 soms to win the competition for future scientists.",
      b21:"Normurodov Olmos",
      p21:"In the 2021/2022 academic year, the scholarship holder of IbraimYusupov",
      b22:"Jaylashova Dilbar",
      p22:"In the 2021/2022 academic year, the scholarship holder of IbraimYusupov",
      b23:"Tolibjonov Saidazimxon Nodirjon o’g’li",
      p23:"Member of the Youth Academy. In the 2021/2022 academic year, he is the recipient of the Tolkien Mirkomilov Academic Scholarship. Winner of the competition Start-Up projects held at the Institute",
    },
    graduates: {
      first:
        "Many gifted youth study at the Tashkent Chemical-Technological Institute. The youth achieve many successes. We are proud of our youth.",
      second: "Gifted students",
    }
  },
};
  export default studentInfo;