const FilialLang = {
  uz: {
    title: "Toshkent kimyo-texnologiya institutining filiallari",
    second: "Toshkent kimyo-texnologiya instituti Yangiyer filiali",
    third: "Toshkent kimyo-texnologiya institutining Shahrisabz filiali",
    site: "Filialning rasmiy web sayti:",
    shahrisabz: {
      title: "TKTI Shahrisabz filiali",
      data: [
        "Qashqadaryo viloyatida oziq-ovqat mahsulotlari ishlab chiqarish sanoati salohiyatini yanada oshirish va iqtisodiyotning bazaviy tarmoqlarida oliy maʼlumotli kadrlar tayyorlashni kengaytirish maqsadida Oʻzbekiston Respublikasi Oliy va oʻrta maxsus taʼlim vazirligi, Iqtisodiyot va sanoat vazirligi, Moliya vazirligi va Qashqadaryo viloyati hokimligining Qashqadaryo viloyatining Shahrisabz shahrida Toshkent kimyo-texnologiya institutining Shahrisabz filialini (keyingi oʻrinlarda Filial deb ataladi) tashkil etish toʻgʻrisidagi taklifiga rozilik berilgan.",
        "Filialning asosiy vazifalari quyidagilar:",
        "hududda kimyo va oziq-ovqat sanoati sohasining rivojlanish istiqbollari va ustuvor vazifalarini, zamonaviy texnika hamda texnologik tendentsiyalarni hisobga olgan holda ehtiyoj yuqori boʻlgan mutaxassisliklar boʻyicha amaliy koʻnikmalarni egallagan malakali kadrlarni tayyorlash",
        "oʻquv va ilmiy loyihalarni amalga oshirish, taʼlim va ilmiy izlanishlar jarayoniga malakali mutaxassislarni keng jalb etish maqsadida ishlab chiqarish va qayta ishlash sohalaridagi respublika va xorijiy etakchi oliy taʼlim muassasalari va ilmiy markazlar bilan hamkorlik aloqalarini kuchaytirish;",
        "kimyo va oziq-ovqat texnologiyalarining barcha yoʻnalishlari boʻyicha malakali kadrlarni tayyorlash va qayta tayyorlash, korxonalarning muammolarini hal etishga qaratilgan innovatsion tadqiqotlarni faol rivojlantirish;",
        "respublika va xorijiy oliy taʼlim muassasalari hamda ilmiy markazlarga istiqbolli yosh bitiruvchilarni magistratura va doktoranturaga muntazam yuborish orqali Filialning ilmiy-pedagogik salohiyatini oshirib borish;",
        "Filialning mintaqa va xalqaro miqyosdagi nufuzini oshirish maqsadida chet el fuqarolari uchun taʼlim olish imkoniyatini kengaytirish va ilgʻor xalqaro tajribani tatbiq qilish;",
        "vebinar taʼlim usullarini joriy etish va rivojlantirish.",
        "Filialda oʻquv jarayoni 2019/2020 oʻquv yilidan boshlangan.",
      ],
    },
    yangiyer: {
      title: "TKTI Yangiyer filiali",
      data: [
        "O‘zbekiston Respublikasi Vazirlar Mahkamasining 2019 yil 9 iyuldagi 573-sonli qaroriga asosan Toshkent kimyo-texnologiya instituti Yangier filiali tashkil etilgan.",
        "Filialda hozirda 2020/2021 o‘quv yilida jami 56 nafar professor-o‘qituvchilar faoliyat yuritmoqda, jumladan, 1 nafar akademik, 4 nafar professor, 7 nafar dotsent, 17 nafar katta o‘qituvchi hamda 27 nafar assitsentlar faoliyat yuritib kelmoqda.",
        "2020-2021 o‘quv yili uchun tasdiqlangan namunaviy o‘quv rejalar asosida o‘quv jarayonlari tashkil etildi.",
        "Filialda 6 ta ta’lim yo‘nalishlari bo‘yicha jami 1068 nafar talabalar tahsil olishmoqda. Shundan 1 kurs 747 nafar, 2-kurs 196 nafar, sirtqi ta’lim shaklida 321 nafarni tashkil etadi.",
        "Oliy va o‘rta maxsus ta’lim vazirligi tomonidan tashkil etilgan elektron ta’lim platformasi orqali o‘quv mashg‘ulotlari tashkil etilib borilmoqda.",
        "2020 yil 17 oktabrda O‘zbekiston Respublikasi Bosh vaziri o‘rinbosari B.A.Musaevning Oliy va o‘rta maxsus ta’lim vazirligi mas’ullari hamda vazirlik tassarufidagi oliy ta’lim muassasalari rahbarlari bilan masofaviy tarzda bo‘lib o‘tgan videoselektor yig‘ilishida, oliy ta’lim muassasalarida o‘quv jarayonini an’anaviy tarzda davom ettirish bo‘yicha bir qator ko‘rsatma va topshiriqlar berilganligini inobatga olgan holda o‘quv-uslubiy, tashkiliy-metodik jihatdan tayyorgarlik ko‘rildi.",
        "Joriy yil (2021/2022) o‘quv yili uchun 6 ta yo‘nalish bo‘yicha jami 675 ta shundan, 475 ta kunduzgi 200 ta sirtqini tashkil etmoqda.Kunduzgi 475 ta (shundan davlat granti 85 ta, to‘lov kontrakt asosida 390 ta);",
        "Sirtqi 200 ta (to‘lov kontrakt asosida 200 ta).",
        "Hozirgi kunda Respublikamizda faoliyat yuritayotgan ishlab chiqarish korxonalarining malakali yetuk kadrlarga bo‘lgan ehtiyojidan hamda ta’lim va ishlab chiqarishning o‘zaro integratsiyasini ta’minlash zaruratini inobatga olgan holda filialimiz bilan hamkorlikda Sirdaryo viloyatida faoliyat olib borayotgan korxona va tashkilot rahbarlari bilan hamkorlik ishlar yo‘lga qo‘yilgan.",
        "Hamda bir qator ilmiy tadqiqot institutlari ishlab chiqarish korxonalari bilan, shu jumladan.“Yangier temir-beton konstruksiyalari zavodi” UK, “OKMK Sherobod sement zavodi” OAJ, .“Navoiazot” AJ, “Metal beton sanoat” MChJ, “Maksam-Chirchiq” AJ, “Dehqonobod kaliy zavodi” AJ, “O‘zRFA Umumiy va noorganik kimyo instituti” bilan ilmiy tadqiqot hamda talabalar amaliyotini tashkil etish bo‘yicha hamkorlik qilish bo‘yicha kelishuvlarga erishildi.",
        "Mamlakatimizda qishloq xo‘jaligini diversifikatsiya qilish, mahsulot yetishtirishni ko‘paytirish va eksport qilishga alohida e’tibor qaratilmoqda. Bu yerning unumdorligini oshirish, mineral o‘g‘itlar ishlab chiqarishni talab etmoqda.Shu bois “O‘zkimyosanoat” aksiyadorlik jamiyati tomonidan “Samsung Injinering” kompaniyasi bilan hamkorlikda ammiak va karbamid zavodi qurish rejalashtirilgan.",
      ],
    },
  },
  ru: {
    title: "Филиалы Ташкентского химико-технологического института",
    second: "Янгиерский филиал Ташкентского химико-технологического института",
    third:
      "Шахрисабзский филиал Ташкентского химико-технологического института",
    site: "Официальный сайт филиала:",
    shahrisabz: {
      title: "Шахрисабзский филиал тхти",
      data: [
        "В целях дальнейшего повышения потенциала промышленности по производству пищевых продуктов в Кашкадарьинской области и расширения подготовки кадров с высшим образованием в базовых отраслях экономики Министерство высшего и среднего специального образования, Министерство экономики и промышленности, Министерство финансов и хокимият Кашкадарьинской области Республики Узбекистан образовали в городе Шахрисабз Кашкадарьинской области Шахрисабзский филиал Ташкентского химико-технологического института (далее-филиал). на предложение о создании фонда было дано согласие.",
        "Основными задачами филиала являются:",
        "подготовка квалифицированных кадров, владеющих практическими навыками по востребованным специальностям, с учетом перспектив и приоритетных задач развития химической и пищевой промышленности в регионе, современных технических и технологических тенденций",
        "усиление сотрудничества с ведущими высшими образовательными учреждениями республики и зарубежных стран и научными центрами в сфере производства и переработки с целью реализации учебных и научных проектов, широкого привлечения квалифицированных специалистов в образовательный и научно-исследовательский процесс;",
        "подготовка и переподготовка квалифицированных кадров по всем направлениям химической и пищевой технологии, активное развитие инновационных исследований, направленных на решение задач предприятий;",
        "повышение научно-педагогического потенциала филиала путем регулярного направления перспективных молодых выпускников в магистратуру и докторантуру в республиканские и зарубежные высшие образовательные учреждения и научные центры;",
        "Расширение доступа к образованию для иностранных граждан и внедрение передового международного опыта в целях повышения авторитета филиала в регионе и на международном уровне;",
        "вебинар внедрение и развитие методов обучения.",
        "Учебный процесс в филиале начался с 2019/2020 учебного года.",
      ],
    },
    yangiyer: {
      title: "Янгиерский филиал ТХТИ",
      data: [
        "Постановлением Кабинета Министров Республики Узбекистан от 9 июля 2019 года № 573 образован Янгиерский филиал Ташкентского химико-технологического института.",
        "В настоящее время в филиале в 2020/2021 учебном году работают 56 профессоров, в том числе 1 академик, 4 профессора, 7 доцентов, 17 старших преподавателей и 27 ассистентов.",
        "Учебный процесс организован на основе утвержденных типовых учебных планов на 2020-2021 учебный год.",
        "В филиале обучаются 1068 студентов по 6 направлениям образования. Из них 1 курс составляет 747 человек, 2 курс-196 человек, заочная форма обучения-321 человек.",
        "Через электронную образовательную платформу, созданную Министерством высшего и среднего специального образования, проводятся учебные занятия.",
        "17 октября 2020 года заместитель Премьер-Министра Республики Узбекистан Б.A.Учитывая, что на дистанционном видеоселекторном совещании Мусаева с ответственными лицами Министерства высшего и среднего специального образования, а также руководителями высших образовательных учреждений при Министерстве был дан ряд указаний и поручений по традиционному продолжению учебного процесса в высших образовательных учреждениях, была подготовлена учебно-методическая, организационно-методическая работа.",
        "На текущий (2021/2022) учебный год по 6 направлениям в общей сложности 675 факультетов, 475 очных и 200 заочных.475 на дневном отделении (из них 85 на государственном Гранте, 390 на платной контрактной основе);",
        "200 заочно (оплата 200 на контрактной основе).",
        "Учитывая потребность действующих в настоящее время в Республике производственных предприятий в квалифицированных кадрах и необходимость обеспечения взаимной интеграции образования и производства, совместно с филиалом налажено сотрудничество с руководителями предприятий и организаций, действующих в Сырдарьинской области.",
        "А также ряд научно-исследовательских институтов с производственными предприятиями, в том числе.АО янгиерский завод железобетонных конструкций, ОАО ШЕРАБАДСКИЙ цементный завод ОКМК,.Достигнуты договоренности о сотрудничестве в организации научно-исследовательской и студенческой практики с АО” Навоиазот“, ООО” Металлобетонная Промышленность“, АО” Максам-Чирчик“, АО” Дехканабадский калийный завод“,” Институтом общей и неорганической химии АН РУз.",
        "В нашей стране особое внимание уделяется диверсификации сельского хозяйства, увеличению производства и экспорта продукции. Это требует повышения плодородия земли, выработки минеральных удобрений.В связи с этим акционерным обществом” Узкимесаноат “совместно с компанией” Samsung Engineering  планируется строительство завода по производству аммиака и карбамида.",
      ],
    },
  },
  en: {
    title: "Branches of the Tashkent Institute of Chemical Technology",
    second: "Yangier Branch of Tashkent Institute of Chemical Technology",
    third: "Shakhrisabz branch of Tashkent Institute of Chemical Technology",
    site: "Official website of the branch:",
    shahrisabz: {
      title: "TICT Shahrisabz branch",
      data: [
        "In order to further increase the potential of the food production industry in the Kashkadarya region and expand the training of personnel with higher education in the basic sectors of the economy, the Ministry of Higher and Secondary Special Education, the Ministry of Economy and Industry, the Ministry of Finance and the Khokimiyat of the Kashkadarya region of the Republic of Uzbekistan have established the Shakhrisabz branch of the Tashkent Institute of Chemical Technology (hereinafter -branch). the proposal to create a fund was agreed.",
        "The main tasks of the branch are as follows:",
        "training of qualified personnel possessing practical skills in the field of specialties with high needs, taking into account the development prospects and priority tasks of the chemical and food industry, modern technical and technological trends in the region",
        "cooperation with leading higher educational institutions and scientific centers in the field of production and processing in order to carry out educational and scientific projects, attract qualified specialists to the process of education and research;",
        "active development of innovative research aimed at training and retraining qualified personnel in all areas of chemical and food technologies, solving the problems of enterprises;",
        "to increase the scientific and pedagogical potential of the branch by sending prospective young graduates to master's and doctorate programs to the Republican and foreign higher educational institutions and scientific centers;",
        "In order to increase the prestige of the branch in the region and internationally, expand the opportunities for foreign citizens to receive education and apply advanced international experience;",
        "introduction and development of webinar teaching methods.",
        "The training process in the Branch began in 2019/2020 academic year.",
      ],
    },
    yangiyer: {
      title: "TICT Yangiyer branch",
      data: [
        "According to the decision of the Cabinet of Ministers of the Republic of Uzbekistan dated July 9, 2019 № 573, the Newier branch of the Tashkent chemical and Technological Institute was established.",
        "Currently, the branch has a total of 56 professors and teachers, including 1 academician, 4 professors, 7 associate professors, 17 senior teachers and 27 assistants.",
        "Training processes were organized on the basis of standard training plans approved for the 2020-2021 academic year.",
        "In total, 1068 students are studying in 6 educational areas of the branch. 1 course consists of 747 people, 2-course 196 people, 321 in the form of correspondence education.",
        "Training sessions are organized through the e-learning platform established by the Ministry of higher and secondary special education.",
        "On October 17, 2020, Prime Minister of the Republic of Uzbekistan took place.A.At the video-projector meeting held at a distance with the officials of the Ministry of Higher and secondary special education of Musaev, as well as the heads of the higher educational institutions of the Ministry of Education, a number of instructions and instructions were given for the normal continuation of the educational process in higher educational institutions, educational-methodical, organizational-methodological preparation was",
        "In the current year (2021/2022) for the academic year, a total of 675 pieces of 6 directions of which, 475 pieces of daily 200 correspondence is organized.475 units during the day (of which the state grant is 85 units, payment is 390 units by contract);",
        "Correspondence 200 PCs (payment is by contract 200 PCs).",
        "Taking into account the need for qualified personnel of the production enterprises operating in the Republic, as well as the need to ensure mutual integration of education and production, cooperation with the heads of enterprises and organizations operating in the Syrdarya region has been established in cooperation with our branch.",
        "And a number of scientific research institutes, including with manufacturing enterprises.Yangier reinforced concrete structures plant “UK,” Okmc Sherabad Cement Plant JSC .Agreements were reached on cooperation with” Navoiazot “JSC,” Metal concrete industry “LLC,” Maksam-Chirchik “JSC,” Dekhkanabad potash Plant “JSC,” Institute of General and inorganic chemistry of Uzrfa  for scientific research and organization of student practice.",
        "Particular attention is paid to the diversification of Agriculture in our country, the reproduction and export of crop production. This requires increasing the fertility of the Earth, the production of mineral fertilizers.Therefore, it is planned to build a plant of ammonia and urea in cooperation with Samsung Engineering by the” Uzkimyosanoat “Joint-Stock Company.",
      ],
    },
  },
};

export default FilialLang;